Connect application to the Database
Notes:
Run `pip install SQLAlchemy mysqlclient` to install SQLAlchemy and mysqlclient packages

Fixed Error Messages:
...
  File "/.../nf_streamlit/app/db.py", line 4, in <module>
    conn = st.experimental_connection('users_db', type='sql')
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/streamlit/runtime/connection_factory.py", line 298, in connection_factory
    raise ModuleNotFoundError(f"{str(e)}. {extra_info}")
ModuleNotFoundError: No module named 'MySQLdb'. You need to install the 'mysqlclient' package to use this connection.

...
Collecting mysqlclient
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/.../nf_streamlit/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/.../nf_streamlit/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/.../nf_streamlit/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-mxkfmcmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-mxkfmcmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-mxkfmcmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

...
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run db.py [ARGUMENTS]
Traceback (most recent call last):
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

...
Traceback (most recent call last):
  File "/.../nf_streamlit/app/db.py", line 8, in <module>
    s.execute('CREATE TABLE IF NOT EXISTS drea_users (person TEXT, pet TEXT);')
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2042, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 638, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 631, in _text_coercion
    return _no_text_coercion(element, argname)
  File "/.../nf_streamlit/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 601, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'CREATE TABLE IF NOT EXIST...' should be explicitly declared as text('CREATE TABLE IF NOT EXIST...')

References:
pandas.DataFrame.to_dict — pandas 2.1.1 documentation
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html#pandas-dataframe-to-dict

dictionary - Python update a key in dict if it doesn't exist - Stack Overflow
https://stackoverflow.com/questions/42315072/python-update-a-key-in-dict-if-it-doesnt-exist
https://stackoverflow.com/a/42315120
https://stackoverflow.com/questions/42315072/python-update-a-key-in-dict-if-it-doesnt-exist/42315120#42315120

Deep copy of a dict in python - Stack Overflow
https://stackoverflow.com/questions/5105517/deep-copy-of-a-dict-in-python

Python | Intersect two dictionaries through keys - GeeksforGeeks
https://www.geeksforgeeks.org/python-intersect-two-dictionaries-through-keys/

st.connections.SQLConnection - Streamlit Docs
https://docs.streamlit.io/library/api-reference/connections/st.connections.sqlconnection
https://docs.streamlit.io/library/api-reference/connections/st.connections.sqlconnection#sqlconnectionquery
https://docs.streamlit.io/library/api-reference/connections/st.connections.sqlconnection#:~:text=Users%20of%20this%20connection%20should%20use%20the%20contextmanager%20pattern%20for%20writes%2C%20transactions%2C%20and%20anything%20more%20complex%20than%20simple%20read%20queries.

SQL PRIMARY KEY Constraint
https://www.w3schools.com/sql/sql_primarykey.ASP

sql - MySQL error: key specification without a key length - Stack Overflow
https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length
https://stackoverflow.com/a/1827099
https://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length/1827099#1827099

[sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2005, "Unknown MySQL server host ]
Error Messages — SQLAlchemy 2.0 Documentation
https://docs.sqlalchemy.org/en/20/errors.html#error-e3q8

Problem installing mysqlclient - Can not find valid pkg-config name - ☁️ Streamlit Community Cloud - Streamlit
https://discuss.streamlit.io/t/problem-installing-mysqlclient-can-not-find-valid-pkg-config-name/47108/2
[apt install libmysqlclient-dev]

"Unknown MySQL server host" when using Flask in Python - Stack Overflow
https://stackoverflow.com/questions/47825384/unknown-mysql-server-host-when-using-flask-in-python

Introducing st.experimental_connection!
https://blog.streamlit.io/introducing-st-experimental_connection/
https://blog.streamlit.io/introducing-st-experimental_connection/#step-2-set-up-credentials-and-connection-information-in-streamlitsecretstoml

Connecting to data - Streamlit Docs
https://docs.streamlit.io/library/advanced-features/connecting-to-data
https://docs.streamlit.io/library/advanced-features/connecting-to-data#global-secrets-managing-multiple-apps-and-multiple-data-stores

HTML URL Encoding Reference
https://www.w3schools.com/tags/ref_urlencode.ASP

how to escape special characters in mysql jdbc connection string - Stack Overflow
https://stackoverflow.com/questions/13984567/how-to-escape-special-characters-in-mysql-jdbc-connection-string