Fix error about calling `set_page_config()` first
Notes:
The warning about ensuring `set_page_config()` is called first was due to
the import order which imports `login.py` from `views` which in turn
calles `get_credentials` from the `db` database service as the first
function in [line 9](https://github.com/MoCoMakers/nf_streamlit/blob/3dd8c47d645694cd8aa6f40b48e8e7c7840d6e38/app/views/login.py#L9)

Fixed Error Messages:
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/app.py", line 4, in <module>
    st.set_page_config(layout="wide", page_title="Hack4NF Drug Response Data Visualization")
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/streamlit/commands/page_config.py", line 260, in set_page_config
    ctx.enqueue(msg)
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_run_context.py", line 130, in enqueue
    raise StreamlitAPIException(
streamlit.errors.StreamlitAPIException: `set_page_config()` can only be called once per app page, and must be called as the first Streamlit command in your script.
For more information refer to the [docs](https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config).

References:
st.set_page_config - Streamlit Docs
https://docs.streamlit.io/develop/api-reference/configuration/st.set_page_config