Fix DataFrame pagination configuration
Notes:
Using `AgGrid`'s' `gridOptions` parameter causes `gb.configure_pagination()` to be ignored.
However, this does not fix the error message

Error Messages:
MessageSizeError: Data of size 228.3 MB exceeds the message size limit of 200.0 MB.
This is often caused by a large chart or dataframe. Please decrease the amount of data sent to the browser, or increase the limit by setting the config option server.maxMessageSize. Click here to learn more about config options.
Note that increasing the limit may lead to long loading times and large memory consumption of the client's browser and the Streamlit server.

References:
Streamlit message size error fix — Restack
https://www.restack.io/docs/streamlit-knowledge-streamlit-message-size-error-fix

GridOptionsBuilder — streamlit-aggrid 0.2.3 documentation
https://streamlit-aggrid.readthedocs.io/en/docs/GridOptionsBuilder.html
https://streamlit-aggrid.readthedocs.io/en/docs/GridOptionsBuilder.html#st_aggrid.grid_options_builder.GridOptionsBuilder
https://streamlit-aggrid.readthedocs.io/en/docs/GridOptionsBuilder.html#:~:text=paginationPageSize%20%E2%80%93%20Forces%20page%20to%20have%20this%20number%20of%20rows%20per%20page.%20Defaults%20to%2010.
https://streamlit-aggrid.readthedocs.io/en/docs/GridOptionsBuilder.html#st_aggrid.grid_options_builder.GridOptionsBuilder:~:text=paginationPageSize%20%E2%80%93%20Forces%20page%20to%20have%20this%20number%20of%20rows%20per%20page.%20Defaults%20to%2010.

JavaScript Grid: Row Pagination | AG Grid
https://www.ag-grid.com/javascript-data-grid/row-pagination/#example-customising-pagination

How to improve Aggrid speed? - 🎈 Using Streamlit - Streamlit
https://discuss.streamlit.io/t/how-to-improve-aggrid-speed/36741

config.toml - Streamlit Docs
https://docs.streamlit.io/develop/api-reference/configuration/config.toml

Paginating dataframes with Streamlit | by Carlos D Serrano | Streamlit | Medium
https://medium.com/streamlit/paginating-dataframes-with-streamlit-2da29b080920