Fix error misspelling of `deploy_location` dictionary
Notes:
The `deploy_location` is used to set where the code is being deployed.
It is set to `local` for local developement environments.

Fixed Error Messages:
Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
KeyError: 'deploy_location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/nf_streamlit/app/Home.py", line 12, in <module>
    from views import login
  File "/app/nf_streamlit/app/views/login.py", line 6, in <module>
    from db import get_credentials, update_user
  File "/app/nf_streamlit/app/db.py", line 4, in <module>
    if st.secrets["deploy_location"]["location"]=="local":
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 311, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.secrets has no key "deploy_location". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management'
2024-08-06 16:01:57.848 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
KeyError: 'deploy_location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/nf_streamlit/app/Home.py", line 12, in <module>
    from views import login
  File "/app/nf_streamlit/app/views/login.py", line 6, in <module>
    from db import get_credentials, update_user
  File "/app/nf_streamlit/app/db.py", line 4, in <module>
    if st.secrets["deploy_location"]["location"]=="local":
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 311, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.secrets has no key "deploy_location". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management'
2024-08-06 16:07:22.078 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
KeyError: 'deploy_location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/nf_streamlit/app/Home.py", line 12, in <module>
    from views import login
  File "/app/nf_streamlit/app/views/login.py", line 6, in <module>
    from db import get_credentials, update_user
  File "/app/nf_streamlit/app/db.py", line 4, in <module>
    if st.secrets["deploy_location"]["location"]=="local":
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/secrets.py", line 311, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.secrets has no key "deploy_location". Did you forget to add it to secrets.toml or the app settings on Streamlit Cloud? More info: https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management'

References:
TOML: English v1.0.0
https://toml.io/en/v1.0.0
https://toml.io/en/v1.0.0#table

secrets.toml - Streamlit Docs
https://docs.streamlit.io/develop/api-reference/connections/secrets.toml

Secrets management - Streamlit Docs
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#use-secrets-in-your-app
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#use-secrets-in-your-app:~:text=You%20can%20access%20st.secrets%20via%20attribute%20notation%20(e.g.%20st.secrets.key)%20or%20key%20notation%20(e.g.%20st.secrets%5B%22key%22%5D)%20%E2%80%94%20just%20like%20st.session_state.
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#:~:text=Rather%20than%20passing%20each%20secret%20as%20attributes%20in%20a%20function%2C%20you%20can%20more%20compactly%20pass%20the%20section%20to%20achieve%20the%20same%20result.%20You%20can%20use%20Python%27s%20unpacking%20notation%20like%20the%20following%20example%20which%20uses%20the%20secrets%20above%3A

Configuration - Streamlit Docs
https://docs.streamlit.io/library/advanced-features/configuration