Fix error from using wrong data type in `secrets.toml.example` file
Notes:
Though `secrets.toml.example` is a template file, I
want it to have values that can let the project run
on startup. The values in the `cookie` dictionary are
supposed to be changed, but the existing string values
can be used except the `expiry_days: "CHANGE-EXPIRY-DAYS"`
key-value pair which results in an error because an integer
value is expected.

Fixed Error Messages:
Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/nf_streamlit/app/Home.py", line 13, in <module>
    login.loginapp()
  File "/app/nf_streamlit/app/views/login.py", line 51, in loginapp
    name, authentication_status, username = authenticator.login(
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/__init__.py", line 208, in login
    self.cookie_handler.set_cookie()
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 71, in set_cookie
    self.exp_date = self._set_exp_date()
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 84, in _set_exp_date
    return (datetime.utcnow() + timedelta(days=self.cookie_expiry_days)).timestamp()
TypeError: unsupported type for timedelta days component: str
Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/app/nf_streamlit/app/Home.py", line 13, in <module>
    login.loginapp()
  File "/app/nf_streamlit/app/views/login.py", line 51, in loginapp
    name, authentication_status, username = authenticator.login(
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/__init__.py", line 208, in login
    self.cookie_handler.set_cookie()
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 71, in set_cookie
    self.exp_date = self._set_exp_date()
  File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 84, in _set_exp_date
    return (datetime.utcnow() + timedelta(days=self.cookie_expiry_days)).timestamp()
TypeError: unsupported type for timedelta days component: str

TypeError: unsupported type for timedelta days component: str
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/app/nf_streamlit/app/Home.py", line 13, in <module>
    login.loginapp()
File "/app/nf_streamlit/app/views/login.py", line 51, in loginapp
    name, authentication_status, username = authenticator.login(
File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/__init__.py", line 208, in login
    self.cookie_handler.set_cookie()
File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 71, in set_cookie
    self.exp_date = self._set_exp_date()
File "/usr/local/lib/python3.9/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 84, in _set_exp_date
    return (datetime.utcnow() + timedelta(days=self.cookie_expiry_days)).timestamp()

References:
TOML: English v1.0.0
https://toml.io/en/v1.0.0
https://toml.io/en/v1.0.0#table

secrets.toml - Streamlit Docs
https://docs.streamlit.io/develop/api-reference/connections/secrets.toml

Secrets management - Streamlit Docs
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#use-secrets-in-your-app
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#use-secrets-in-your-app:~:text=You%20can%20access%20st.secrets%20via%20attribute%20notation%20(e.g.%20st.secrets.key)%20or%20key%20notation%20(e.g.%20st.secrets%5B%22key%22%5D)%20%E2%80%94%20just%20like%20st.session_state.
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management#:~:text=Rather%20than%20passing%20each%20secret%20as%20attributes%20in%20a%20function%2C%20you%20can%20more%20compactly%20pass%20the%20section%20to%20achieve%20the%20same%20result.%20You%20can%20use%20Python%27s%20unpacking%20notation%20like%20the%20following%20example%20which%20uses%20the%20secrets%20above%3A

Configuration - Streamlit Docs
https://docs.streamlit.io/library/advanced-features/configuration