Fix error that emerged if the DataFrame `dm_merged` is empty
Notes:
While trying to reduce the size of the DataFrames, the filtered DataFrame `dm_merged` was empty and caused an error

Fixed Error Messages:
AttributeError: 'NoneType' object has no attribute 'to_csv'

Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/app/pages/Delta_S_Prime.py", line 145, in <module>
    data=dm_merged.to_csv().encode('utf-8'),

2024-07-14 14:26:49.073 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/Delta_S_Prime.py", line 145, in <module>
    data=dm_merged.to_csv().encode('utf-8'),
AttributeError: 'NoneType' object has no attribute 'to_csv'

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/app/pages/Delta_S_Prime.py", line 159, in <module>
    if dm_merged:
File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(

2024-07-14 14:52:05.075 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/Delta_S_Prime.py", line 159, in <module>
    if dm_merged:
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/app/pages/Delta_S_Prime.py", line 145, in <module>
    data=dm_merged.to_csv().encode('utf-8'),

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/Delta_S_Prime.py", line 169, in <module>
    df_ref_group = dm_merged.loc[dm_merged[active_gene] == 0]
AttributeError: 'NoneType' object has no attribute 'loc'